### teste de buscar todos os clientes
GET http://localhost:40000/getAllClientes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InF3ZSIsImlhdCI6MTY5Mjc5ODg2MSwiZXhwIjoxNjkyNzk5NDYxfQ.43OGaDLf0iQHUXgfM8wBETYE5A8TGHR1G0hfupccsfM

{    
    
}

### teste de buscar aluno por ID
POST http://localhost:40000/GetClientesByID HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    "clienteid": 2
}

### teste de inserção de aluno
POST http://localhost:40000/InsertClientes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzM0ODE2NDEsInVzZXJuYW1lIjoicXdlIn0.LRKs8uvt-SJ9E9dMGYRkCs7HhMDlqVmwap_zcaoONeQ

{    
    "clienteid": 0,
    "codigo": "CLI05",
    "nome": "Scarlet Vitoria do Carmo",
    "nome": "Rua Rio Grande",
    "ativo": true,
    "deleted": false    
}

### teste de atualização de aluno
POST http://localhost:40000/UpdateClientes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzM0ODE2NDEsInVzZXJuYW1lIjoicXdlIn0.LRKs8uvt-SJ9E9dMGYRkCs7HhMDlqVmwap_zcaoONeQ

{    
    "cursoid": 9,
    "codigo": "xfisio",
    "descricao": "xBacharelado em Fisioterapia",
    "ativo": true,
    "deleted": false 
}

### teste de atualização de aluno
POST http://localhost:40000/DeleteClientes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzM0ODE2NDEsInVzZXJuYW1lIjoicXdlIn0.LRKs8uvt-SJ9E9dMGYRkCs7HhMDlqVmwap_zcaoONeQ

{    
    "cursoid": 9   
}